<a href="https://colab.research.google.com/github/tina287/fianceHomework/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import requests

import pandas as pd

# 處理時間
import datetime as dt

id = '2330'

date = dt.date.today().strftime("%Y%m%d")

stock_data = requests.get(f'https://www.twse.com.tw/rwd/zh/ \
            afterTrading/STOCK_DAY?date={date}&stockNo={id}')

# 轉換JSON格式
json_data = stock_data.json()


a = pd.DataFrame(data=json_data['data'],
                  columns=json_data['fields'])

a

,日期,成交股數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,成交筆數
0,113/09/02,"19,272,593","18,270,058,260",950.00,955.00,943.00,948.00,+4.00,"31,642"
1,113/09/03,"23,205,623","21,908,471,541",948.00,952.00,939.00,940.00,-8.00,"47,139"
2,113/09/04,"93,169,835","83,424,133,824",894.00,905.00,888.00,889.00,-51.00,"393,210"
3,113/09/05,"34,147,890","30,998,595,394",907.00,915.00,900.00,902.00,+13.00,"63,902"
4,113/09/06,"28,248,063","25,786,016,936",909.00,918.00,903.00,918.00,+16.00,"38,415"
5,113/09/09,"38,448,946","34,456,838,126",892.00,900.00,891.00,899.00,-19.00,"102,365"
6,113/09/10,"34,312,646","31,067,424,234",907.00,911.00,901.00,904.00,+5.00,"45,141"
7,113/09/11,"19,513,256","17,621,000,956",906.00,906.00,900.00,901.00,-3.00,"30,789"
8,113/09/12,"43,749,260","40,999,951,508",936.00,944.00,928.00,940.00,X0.00,"80,643"
9,113/09/13,"28,307,441","26,795,862,243",955.00,955.00,939.00,947.00,+7.00,"39,071"
10,113/09/16,"14,456,888","13,692,259,575",952.00,952.00,943.00,947.00,0.00,"26,421"
11,113/09/18,"30,094,662","28,303,054,525",945.00,948.00,933.00,941.00,-6.00,"46,622"
12,113/09/19,"35,254,383","33,482,773,635",940.00,960.00,936.00,960.00,+19.00,"53,494"
13,113/09/20,"66,762,167","65,105,344,444",981.00,982.00,971.00,973.00,+13.00,"67,911"
14,113/09/23,"15,399,658","15,013,916,758",971.00,977.00,971.00,977.00,+4.00,"26,106"
15,113/09/24,"29,324,170","28,726,805,585",976.00,987.00,971.00,987.00,+10.00,"63,433"
16,113/09/25,"43,039,991","43,053,012,337","1,000.00","1,005.00",998.00,"1,005.00",+18.00,"82,005"

In [13]:
import yfinance as yf
from datetime import datetime

def get_tsmc_stock_data():
    # 獲取台積電股票的 ticker 對象
    tsmc = yf.Ticker("2330.TW")

    # 獲取當前股票信息
    info = tsmc.info

    # 獲取最新的股價數據
    history = tsmc.history(period="1d")

    # 獲取當前時間
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return {
        "時間": current_time,
        "股價": history['Close'].iloc[-1] if not history.empty else "N/A",
        "漲跌": f"{history['Close'].iloc[-1] - history['Open'].iloc[-1]:.2f}" if not history.empty else "N/A",
        "成交量": info.get('volume', "N/A"),
        "52週高點": info.get('fiftyTwoWeekHigh', "N/A"),
        "52週低點": info.get('fiftyTwoWeekLow', "N/A"),
        "市值": info.get('marketCap', "N/A")
    }

if __name__ == "__main__":
    data = get_tsmc_stock_data()
    print("台積電(2330.TW)股市資料:")
    for key, value in data.items():
        print(f"{key}: {value}")

台積電(2330.TW)股市資料:
時間: 2024-09-25 14:41:22
股價: 1005.0
漲跌: 5.00
成交量: 42094049
52週高點: 1080.0
52週低點: 516.0
市值: 26060051709952